from fastapi import APIRouter
from brain.missions.mission_scheduler import mission_scheduler

router = APIRouter()

@router.get("/reflection/insights")
def get_reflection_insights():
    """
    Returns insights generated by the Reflection Engine.
    """
    engine = mission_scheduler.reflection_engine
    return {
        "insights": engine.insights,
        "last_signal": engine.last_reflection_signal,
        "confidence": engine.reflection_confidence,
        "buffer_size": len(engine.event_buffer)
    }
